[config.wallpaper]
command = "swww"
arguments = ["img", "--resize fit", "--transition-type none"]
set = false 

[templates.hyprland]
input_path = './templates/hyprland-colors.css'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.dunst]
input_path = './templates/dunstrc-colors'
output_path = '~/.config/dunst/dunstrc'
