#!/bin/bash
### === Autostart === ###
xrandr --rate 144 &
xrdb -load $HOME/.config/.Xresources &
dunst -conf $HOME/.config/dunst/dunstrc &
pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-fill --randomize $HOME/Pictures/Wallpapers/* &
$HOME/.config/polybar/launch.sh &
fcitx -d &

# Workspaces
bspc monitor -d 1 2 3 4 5

# xsetroot -cursor_name left_ptr
 
bspc config border_width	0
bspc config top_padding     30
bspc config window_gap		12
bspc config split_ratio		0.5
bspc config focus_follows_pointer	true
# bspc config pointer_modifier	mod1
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#2e3440"
bspc config automatic_scheme	spiral
 
# bspc rule -a Firefox desktop='^2'
